Repository legend-exp/LegendSpecFits.jl, pull requests merged in 2024-12, with the labels that each got.

#83 Fixed sipm peak search
  src/sipm_simple_calibration.jl
Labels: enhancement

#96 Bug fix SiPM calibration
  src/sipmfit.jl
Labels: bug, enhancement

#87 A/E ctc correction
  src/LegendSpecFits.jl
  src/aoe_ctc.jl
  src/aoe_pseudo_prior.jl
Labels: enhancement

#93 add ft_fwhm_tol to avoid artificially large ft in filter opt
  src/filter_optimization.jl
Labels: enhancement

#100 Deprecate functions: `surrival` --> `survival`
  ext/LegendSpecFitsRecipesBaseExt.jl
  src/aoe_cut.jl
  src/aoe_filter_optimization.jl
  src/qc.jl
Labels: breaking

#101 Replace `e_expression` in `ctc_aoe` by `qdrift_expression`
  src/aoe_ctc.jl
Labels: enhancement

#109 Updates to `auto_calibration`
  src/auto_calibration.jl
Labels: bug, enhancement

#111 Add Downgrade CI and update lower package compats
  .github/workflows/Downgrade.yml
  Project.toml
  test/Project.toml
  test/test_utils.jl
Labels: dependencies
