Repository legend-exp/LegendSpecFits.jl, pull requests merged in 2024-10, with the labels that each got.

#73 Bug Fixes in MLE fits
  Project.toml
  ext/LegendSpecFitsRecipesBaseExt.jl
  src/LegendSpecFits.jl
  src/aoe_fit_calibration.jl
  src/aoefit.jl
  src/aoefit_combined.jl
  src/chi2fit.jl
  src/ctc.jl
  src/fit_calibration.jl
  src/fit_fwhm.jl
  src/lqfit.jl
  src/memory_utils.jl
  src/peakshapes.jl
  src/peakstats.jl
  src/pseudo_prior.jl
  src/simple_calibration.jl
  src/singlefit.jl
  src/specfit.jl
Labels: bug

#72 Peakwise fit function for calibration peak fits
  src/pseudo_prior.jl
  src/specfit.jl
  src/specfit_functions.jl
  test/test_utils.jl
Labels: bug, enhancement

#71 Update µ and σ recipe
  ext/LegendSpecFitsRecipesBaseExt.jl
Labels: bug

#67 ctc plot recipe
  Project.toml
  ext/LegendSpecFitsRecipesBaseExt.jl
Labels: bug

#78 A/E fitting
  Project.toml
  ext/LegendSpecFitsRecipesBaseExt.jl
  src/LegendSpecFits.jl
  src/aoe_cut.jl
  src/gof.jl
  src/peakstats.jl
  src/pseudo_prior.jl
  src/specfit.jl
  src/utils.jl
Labels: bug

#76 Simple calibration function for SiPMs
  src/LegendSpecFits.jl
  src/sipm_simple_calibration.jl
Labels: enhancement

#81 Improve performance of `get_mc_value_shapes` and `estimate_fwhm`
  src/specfit.jl
  src/utils.jl
Labels: performace
