Repository legend-exp/LegendSpecFits.jl, pull requests merged in 2024-11, with the labels that each got.

#86 Remove unused packages from `Project.toml` in tests
  test/Project.toml
Labels: dependencies

#88 Sipm calibration routines
  Project.toml
  ext/LegendSpecFitsRecipesBaseExt.jl
  src/LegendSpecFits.jl
  src/fit_calibration.jl
  src/gof.jl
  src/sipm_simple_calibration.jl
  src/sipmfit.jl
Labels: enhancement

#74 Lq updated
  ext/LegendSpecFitsRecipesBaseExt.jl
  src/aoe_cut.jl
  src/lqcut.jl
  src/singlefit.jl
  test/runtests.jl
  test/test_lq.jl
Labels: bug, enhancement

#92 change pseudo-prior on skew_width to more restrictive value
  src/pseudo_prior.jl
Labels: enhancement
