Repository legend-exp/LegendSpecFits.jl, pull requests merged in 2025-05, with the labels that each got.

#144 added lq_normalization
  .github/workflows/Downgrade.yml
  Project.toml
  src/lqcut.jl
  test/Project.toml
  test/test_lq.jl
Labels: bug

#149 Simple cal
  src/LegendSpecFits.jl
  src/aoe_cut.jl
  src/aoefit.jl
  src/auto_calibration.jl
  src/ctc.jl
  src/fit_fwhm.jl
  src/simple_calibration.jl
  test/Project.toml
  test/runtests.jl
  test/test_simplecal.jl
  test/test_specfit.jl
  test/test_utils.jl
Labels: enhancement

#154 Reactivate tests on `pre`
  .github/workflows/Downgrade.yml
  .github/workflows/ci.yml
Labels: test
