Repository legend-exp/LegendSpecFits.jl, pull requests merged in 2025-03, with the labels that each got.

#128 Fix argument type of `fit_enc_sigmas`
  src/filter_optimization.jl
Labels: bug

#132 Replace all report `Dicts` by `OrderedDict`
  Project.toml
  src/LegendSpecFits.jl
  src/aoe_cut.jl
  src/aoefit.jl
  src/aoefit_combined.jl
  src/lqfit.jl
  src/specfit.jl
Labels: enhancement, dependencies

#131 Require `peakfinder_σ_scaled` in `sipm_simple_calibration` to be an integer
  src/sipm_simple_calibration.jl
Labels: bug

#135 Bug Fix `A/E` CTC
  ext/LegendSpecFitsRecipesBaseExt.jl
  src/aoe_ctc.jl
  src/aoe_pseudo_prior.jl
Labels: enhancement

#137 Rewrite `get_pe_res`: numerical FWHM calculation
  src/sipmfit.jl
Labels: bug, breaking

#138 `A/E` CTC update
  src/aoe_ctc.jl
  src/aoe_pseudo_prior.jl
  src/aoefit.jl
  src/aoefit_functions.jl
  src/peakshapes.jl
  src/singlefit.jl
Labels: bug, enhancement, breaking

#139 SiPM `simple_calibration` fix
  src/sipm_simple_calibration.jl
Labels: enhancement

#140 Patch `CTC` energy
  src/ctc.jl
Labels: bug

#142 Patch A/E combined fit in case of single CC band failing to fit
  src/aoefit_combined.jl
Labels: bug
