Repository legend-exp/LegendSpecFits.jl, pull requests merged in 2025-02, with the labels that each got.

#113 Bugfix in `singlefits.jl`
  ext/LegendSpecFitsRecipesBaseExt.jl
  src/gof.jl
  src/singlefit.jl
Labels: bug, enhancement

#115 σ Plot Label Changes in Reports
  src/LegendSpecFits.jl
  src/aoe_fit_calibration.jl
  src/aoefit_combined.jl
Labels: bug

#116 Remove filtering of `µ` and `σ` in the (individual) A/E correction fit
  src/aoe_fit_calibration.jl
Labels: bug

#107 renamed variables in lq_cut, changed expression handling
  ext/LegendSpecFitsRecipesBaseExt.jl
  src/aoe_cut.jl
  src/lqcut.jl
  test/test_lq.jl
Labels: bug, enhancement

#122 Omit performance warning when creating `OptimizationProblem`
  src/aoe_ctc.jl
  src/aoefit.jl
  src/aoefit_combined.jl
  src/chi2fit.jl
  src/ctc.jl
  src/lqfit.jl
  src/singlefit.jl
  src/specfit.jl
Labels: performace

#121 Add A/E ctc plot recipe
  ext/LegendSpecFitsRecipesBaseExt.jl
  src/aoe_ctc.jl
Labels: bug, enhancement

#120 Patch `sipm_simple_calibration`
  Project.toml
  src/LegendSpecFits.jl
  src/sipm_simple_calibration.jl
Labels: bug, enhancement

#123 Bug Fix LQ plot recipes
  ext/LegendSpecFitsRecipesBaseExt.jl
Labels: bug

#125 Bug Fix `fit_calibration`
  src/fit_calibration.jl
Labels: bug

#126 Added missing bracket
  src/lqcut.jl
Labels: bug

#124 updated LQ sideband selection logic
  ext/LegendSpecFitsRecipesBaseExt.jl
  src/lqcut.jl
Labels: bug
