Repository legend-exp/LegendSpecFits.jl, pull requests merged in 2025-04, with the labels that each got.

#148 Add minimal fit function for gamma peaks
  src/pseudo_prior.jl
  src/specfit.jl
  src/specfit_functions.jl
  test/test_fit_chisq.jl
  test/test_specfit.jl
Labels: enhancement

#147 add special handling for case when dof = 0
  src/chi2fit.jl
  test/test_fit_chisq.jl
Labels: bug, enhancement

#150 add exception when rt are out of range and all enc values are NaN
  .github/workflows/Downgrade.yml
  .github/workflows/ci.yml
  Project.toml
  src/filter_optimization.jl
  src/simple_cuts.jl
  test/runtests.jl
  test/test_filter_optimization.jl
Labels: bug, dependencies, test

#152 Exclude `Plots` extension from codecov
  .codecov.yml
Labels: test
